---
swagger: "2.0"
info:
  description: "APIs to cater Block Reservation related asynchronous functionality\
    \ in OPERA.<br /><br /><p>This document and all content within is available under\
    \ the Universal Permissive License v 1.0 (http://oss.oracle.com/licenses/upl).\
    \ Copyright c 2021 Oracle and/or its affiliates.</p>"
  version: "21.1"
  title: "Early Release OPERA Cloud Block Reservation Asynchronous API"
  termsOfService: "https://www.oracle.com/legal/terms.html"
  contact:
    email: "hospitality_apis_ww_grp@oracle.com"
  license:
    name: "UPL"
    url: "https://opensource.org/licenses/upl"
basePath: "/blk/async/v0"
tags:
- name: "BlockAsync"
  description: "The Block Async Service Web Service provides capability to implement\
    \ block related asynchronous operations in OPERA Cloud."
schemes:
- "https"
produces:
- "application/json"
paths:
  /externalSystems/{extSystemCode}/hotels/{hotelId}/blocks/allocationSummary:
    post:
      tags:
      - "BlockAsync"
      summary: "This API facilitates fetching block allocation summary for a Hotel."
      description: "This API will fetch Block allocation information for a hotel,\
        \ and specified date range.  The block allocated inventory, rates and room\
        \ type statistics are returned as part of the response. <p><strong>OperationId:</strong>startBlockAllocationSummaryProcess</p>"
      operationId: "startBlockAllocationSummaryProcess"
      parameters:
      - name: "hotelId"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "extSystemCode"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - in: "body"
        name: "criteria"
        description: "Request object for fetching block allocation summary asynchronously."
        required: true
        schema:
          $ref: "#/definitions/criteria"
      - name: "authorization"
        in: "header"
        description: "Bearer token that needs to be passed which is generated post\
          \ user authentication"
        required: true
        type: "string"
      - name: "x-app-key"
        in: "header"
        description: "Client or Partner’s Application Key"
        required: true
        type: "string"
        pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
      - name: "x-hotelid"
        in: "header"
        description: "Mandatory parameter to identify the hotel code where the end\
          \ user is logged in"
        required: true
        type: "string"
      - name: "Accept-Language"
        in: "header"
        description: "Language code"
        required: false
        type: "string"
      responses:
        "202":
          description: "Location of process status resource"
          headers:
            Content-Language:
              type: "string"
              description: "Audience language"
              pattern: "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"
              x-example: "en-GB"
            Location:
              type: "string"
              description: "Location of process status resource"
      x-interaction:
      - "async-polling"
  /externalSystems/{extSystemCode}/hotels/{hotelId}/blocks/allocationSummary/{requestId}:
    get:
      tags:
      - "BlockAsync"
      summary: "This API returns a hotel's block allocation summary for a scheduled\
        \ process."
      description: "This API will fetch Block allocation information for a hotel,\
        \ and specified date range.  The block allocated inventory, rates and room\
        \ type statistics are returned as part of the response. <p><strong>OperationId:</strong>getBlockAllocationSummary</p>"
      operationId: "getBlockAllocationSummary"
      parameters:
      - name: "requestId"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "hotelId"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "extSystemCode"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "authorization"
        in: "header"
        description: "Bearer token that needs to be passed which is generated post\
          \ user authentication"
        required: true
        type: "string"
      - name: "x-app-key"
        in: "header"
        description: "Client or Partner’s Application Key"
        required: true
        type: "string"
        pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
      responses:
        "200":
          description: "Callback request object for fetched block allocation summary."
          headers:
            Content-Language:
              type: "string"
              description: "Audience language"
              pattern: "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"
              x-example: "en-GB"
          schema:
            $ref: "#/definitions/blockAllocationSummary"
        "204":
          description: "BlockAllocationSummary not found."
    head:
      tags:
      - "BlockAsync"
      summary: "This API returns the status of asynchronous process scheduled for\
        \ given id."
      description: " <p><strong>OperationId:</strong>getBlockAllocationSummaryProcessStatus</p>"
      operationId: "getBlockAllocationSummaryProcessStatus"
      parameters:
      - name: "requestId"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "extSystemCode"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "hotelId"
        in: "path"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "authorization"
        in: "header"
        description: "Bearer token that needs to be passed which is generated post\
          \ user authentication"
        required: true
        type: "string"
      - name: "x-app-key"
        in: "header"
        description: "Client or Partner’s Application Key"
        required: true
        type: "string"
        pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
      - name: "x-hotelid"
        in: "header"
        description: "Mandatory parameter to identify the hotel code where the end\
          \ user is logged in"
        required: true
        type: "string"
      - name: "Accept-Language"
        in: "header"
        description: "Language code"
        required: false
        type: "string"
      responses:
        "200":
          description: "Response for status of scheduled asynchronous process."
          headers:
            Content-Language:
              type: "string"
              description: "Audience language"
              pattern: "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"
              x-example: "en-GB"
            Status:
              type: "string"
              description: "Status of the requested process."
              enum:
              - "Processing"
              - "Invalid"
            Cache-Control:
              type: "string"
              description: "number of seconds to wait before polling again."
              x-example: "max-age=10"
        "201":
          description: "Response for status of scheduled asynchronous process."
          headers:
            Content-Language:
              type: "string"
              description: "Audience language"
              pattern: "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"
              x-example: "en-GB"
            Status:
              type: "string"
              description: "Status of the requested process."
              enum:
              - "Completed"
            Location:
              type: "string"
              description: "Location of newly created resource once the status of\
                \ process run is Complete."
definitions:
  exceptionDetailType:
    type: "object"
    properties:
      type:
        type: "string"
        description: "Absolute URI [RFC3986] that identifies the problem type.  When\
          \ dereferenced, it SHOULD provide a human-readable summary of the problem\
          \ (for example, using HTML)."
      title:
        type: "string"
        description: "Short, human-readable summary of the problem.  The summary SHOULD\
          \ NOT change for subsequent occurrences of the problem, except for purposes\
          \ of localization."
      status:
        type: "integer"
        description: "HTTP status code for this occurrence of the problem, set by\
          \ the origin server."
      detail:
        type: "string"
        description: "Human-readable description specific to this occurrence of the\
          \ problem."
      instance:
        type: "string"
        description: "Absolute URI that identifies the specific occurrence of the\
          \ problem.  It may or may not provide additional information if dereferenced."
      o:errorCode:
        type: "string"
        description: "Application error code, which is different from HTTP error code."
      o:errorPath:
        type: "string"
        description: "Path to the problem at the resource or property level."
      o:errorDetails:
        type: "array"
        description: "Details of the error message, consisting of a hierarchical tree\
          \ structure."
        items:
          $ref: "#/definitions/errorInstance"
      links:
        $ref: "#/definitions/links"
    title: "Error Detail"
    description: "Complex type that contains error details for a REST call."
  errorInstance:
    type: "object"
    properties:
      type:
        type: "string"
        description: "Absolute URI [RFC3986] that identifies the problem type.  When\
          \ dereferenced, it SHOULD provide a human-readable summary of the problem\
          \ (for example, using HTML)."
      title:
        type: "string"
        description: "Short, human-readable summary of the problem.  The summary SHOULD\
          \ NOT change for subsequent occurrences of the problem, except for purposes\
          \ of localization."
      status:
        type: "integer"
        description: "HTTP status code for this occurrence of the problem, set by\
          \ the origin server."
      detail:
        type: "string"
        description: "Human-readable description specific to this occurrence of the\
          \ problem."
      instance:
        type: "string"
        description: "Absolute URI that identifies the specific occurrence of the\
          \ problem.  It may or may not provide additional information if dereferenced."
      o:errorCode:
        type: "string"
        description: "Application error code, which is different from HTTP error code."
      o:errorPath:
        type: "string"
        description: "Path to the problem at the resource or property level."
    title: "Error Instance Details"
    description: "Complex type that contains error instance details for a REST call."
  instanceLink:
    type: "object"
    properties:
      href:
        type: "string"
        description: "URI [RFC3986] or URI Template [RFC6570]. If the value is set\
          \ to URI Template, then the \"templated\" property must be set to true."
      rel:
        type: "string"
        description: "Name of the link relation that, in addition to the type property,\
          \ can be used to retrieve link details. For example, href or profile."
      templated:
        type: "boolean"
        description: "Boolean flag that specifies that \"href\" property is a URI\
          \ or URI Template. If the property is a URI template, set this value to\
          \ true. By default, this value is false."
        default: false
      method:
        type: "string"
        description: "HTTP method for requesting the target of the link."
        enum:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
        - "OPTIONS"
        - "HEAD"
      targetSchema:
        type: "string"
        description: "Link to the metadata of the resource, such as JSON-schema, that\
          \ describes the resource expected when dereferencing the target resource.."
      operationId:
        type: "string"
        description: "The operationId of the path you can call to follow this link.\
          \  This allows you to look up not only the path and method, but the description\
          \ of that path and any parameters you need to supply."
      title:
        type: "string"
        description: "Exact copy of the \"summary\" field on the linked operation."
    description: "Metadata describing link description objects that MAY appear in\
      \ the JSON instance representation."
  links:
    type: "array"
    items:
      $ref: "#/definitions/instanceLink"
  blockAllocationSummaryType:
    type: "object"
    properties:
      blockId:
        type: "string"
        description: "A unique identifying value assigned by the creating system.\
          \ The ID attribute may be used to reference a primary-key value within a\
          \ database or in a particular implementation."
        minLength: 0
        maxLength: 80
      masterBlockId:
        type: "string"
        description: "A unique identifying value assigned by the creating system.\
          \ The ID attribute may be used to reference a primary-key value within a\
          \ database or in a particular implementation."
        minLength: 0
        maxLength: 80
      blockCode:
        type: "string"
        description: "Defined block code for the block."
        minLength: 0
        maxLength: 20
      blockName:
        type: "string"
        description: "Name of the block."
        minLength: 0
        maxLength: 2000
      status:
        type: "string"
        description: "Booking Status of the block."
        minLength: 0
        maxLength: 20
      marketCode:
        type: "string"
        description: "Market Code of the block."
        minLength: 0
        maxLength: 20
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      allocationDates:
        type: "array"
        items:
          $ref: "#/definitions/roomAllocationDateType"
        maxItems: 4000
      hotelId:
        type: "string"
        description: "The Hotel Code the block belongs to."
        minLength: 0
        maxLength: 20
      createDateTime:
        type: "string"
        format: "date-time"
        description: "The business date the block was created."
      blockType:
        type: "string"
        description: "Indicates the internal type of the block like G, etc."
        minLength: 0
        maxLength: 1
  roomAllocationDateType:
    type: "object"
    properties:
      allocations:
        type: "array"
        items:
          $ref: "#/definitions/roomAllocationDetailsType"
        maxItems: 4000
      allocationDate:
        type: "string"
        format: "date"
        description: "The block date for which the allocation details are listed."
  roomAllocationDetailsType:
    type: "object"
    properties:
      inventory:
        description: "The break up of projected rooms by occupancy."
        $ref: "#/definitions/blockGridInvType"
      rates:
        description: "The break up of occupancy rates."
        $ref: "#/definitions/blockGridRatesType"
      roomType:
        type: "string"
        description: "The room type for which the allocation details are listed."
        minLength: 0
        maxLength: 20
      originalRooms:
        type: "integer"
        description: "The total original( forecasted ) rooms for the block."
      currentRooms:
        type: "integer"
        description: "The total current( projected + pickup ) rooms for the block."
      pickupRooms:
        type: "integer"
        description: "The total pickup rooms for the block."
  blockGridInvType:
    type: "object"
    properties:
      onePerson:
        type: "integer"
        description: "Indicates the one person inventory value ( occupancy or availability\
          \ )."
      twoPerson:
        type: "integer"
        description: "Indicates the two person inventory value ( occupancy or availability\
          \ )."
      threePerson:
        type: "integer"
        description: "Indicates the three person inventory value ( occupancy or availability\
          \ )."
      fourPerson:
        type: "integer"
        description: "Indicates the four person inventory value ( occupancy or availability\
          \ )."
      sellLimit:
        type: "integer"
        description: "Indicates the sell limit"
    description: "Indicates the inventory values ( occupancy or availability ) per\
      \ person occupancy."
  blockGridRatesType:
    type: "object"
    properties:
      onePerson:
        type: "number"
        description: "Indicates the one person occupancy rate amount."
      twoPerson:
        type: "number"
        description: "Indicates the two person occupancy rate amount."
      threePerson:
        type: "number"
        description: "Indicates the three person occupancy rate amount."
      fourPerson:
        type: "number"
        description: "Indicates the four person occupancy rate amount."
      extraPerson:
        type: "number"
        description: "Indicates the extra person occupancy rate amount."
    description: "Indicates the rate amount values per person occupancy."
  criteria:
    type: "object"
    properties:
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
    description: "Request object for fetching block allocation summary asynchronously."
  blockAllocationSummary:
    type: "array"
    description: "Response object for fetched block allocation summary."
    items:
      $ref: "#/definitions/blockAllocationSummaryType"
    maxItems: 4000
parameters:
  authKey:
    name: "authorization"
    in: "header"
    description: "Bearer token that needs to be passed which is generated post user\
      \ authentication"
    required: true
    type: "string"
  x-app-key:
    name: "x-app-key"
    in: "header"
    description: "Client or Partner’s Application Key"
    required: true
    type: "string"
    pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
  x-hotelid:
    name: "x-hotelid"
    in: "header"
    description: "Mandatory parameter to identify the hotel code where the end user\
      \ is logged in"
    required: true
    type: "string"
  Accept-Language:
    name: "Accept-Language"
    in: "header"
    description: "Language code"
    required: false
    type: "string"
responses:
  "400":
    description: "Bad Request"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "401":
    description: "Unauthorized"
  "403":
    description: "Forbidden"
  "404":
    description: "Resource not found"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "405":
    description: "Method not allowed"
  "406":
    description: "Not acceptable."
  "413":
    description: "Request Entity Too Large"
  "414":
    description: "Request URI Too Large"
  "415":
    description: "Unsupported Media Type"
  "500":
    description: "System Error"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "502":
    description: "Bad Gateway"
  "503":
    description: "Service Unavailable"
externalDocs:
  description: "Find out more about Oracle Hospitality"
  url: "https://docs.oracle.com/en/industries/hospitality/integration_platforms.html"
